//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class fdata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fdata()
        {
            this.keylinks = new HashSet<keylinks>();
            this.hostel_agreement = new HashSet<hostel_agreement>();
            this.hostel_contract = new HashSet<hostel_contract>();
            this.hostel_manual_agreement = new HashSet<hostel_manual_agreement>();
        }
    
        public int npp { get; set; }
        public string fam { get; set; }
        public string nam { get; set; }
        public string otc { get; set; }
        public Nullable<int> pol { get; set; }
        public Nullable<System.DateTime> rogd { get; set; }
        public string stob { get; set; }
        public string stsp { get; set; }
        public string inostr { get; set; }
        public Nullable<int> gragd { get; set; }
        public string nacion { get; set; }
        public string kur { get; set; }
        public Nullable<int> kkor { get; set; }
        public string user { get; set; }
        public Nullable<int> mestogos { get; set; }
        public string mestokladr { get; set; }
        public string mestoadr { get; set; }
        public string mestoindex { get; set; }
        public string svjaz { get; set; }
        public string phones { get; set; }
        public string prof { get; set; }
        public string zakr { get; set; }
        public Nullable<System.DateTime> dkor { get; set; }
        public string sotel { get; set; }
        public string dolgn { get; set; }
        public string email { get; set; }
        public string gorod { get; set; }
        public string raion { get; set; }
        public string fotocheck { get; set; }
        public string webpwd { get; set; }
        public string obshaga { get; set; }
        public Nullable<int> bgos { get; set; }
        public string bkladr { get; set; }
        public string badr { get; set; }
        public string bindex { get; set; }
        public string ppodr { get; set; }
        public Nullable<int> faktgos { get; set; }
        public string faktkladr { get; set; }
        public string faktadr { get; set; }
        public string faktindex { get; set; }
        public Nullable<int> webstep { get; set; }
        public string mestodom { get; set; }
        public string mestokorp { get; set; }
        public string mestokvart { get; set; }
        public string bdom { get; set; }
        public string bkorp { get; set; }
        public string bkvart { get; set; }
        public string faktdom { get; set; }
        public string faktkorp { get; set; }
        public string faktkvart { get; set; }
        public Nullable<int> vozvrat { get; set; }
        public Nullable<System.DateTime> dr { get; set; }
        public string gal_nation { get; set; }
        public Nullable<bool> gal_validated { get; set; }
        public string obraz_full { get; set; }
        public Nullable<int> C_goodnpp { get; set; }
        public string kfb { get; set; }
        public Nullable<int> clink { get; set; }
        public string kfb1 { get; set; }
        public string inn { get; set; }
        public string snils { get; set; }
        public Nullable<System.DateTime> kfbdr { get; set; }
        public Nullable<int> rgos { get; set; }
        public string rkladr { get; set; }
        public string radr { get; set; }
        public string rindex { get; set; }
        public string rdom { get; set; }
        public string rkorp { get; set; }
        public string rkvart { get; set; }
        public Nullable<int> afilesphoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<keylinks> keylinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hostel_agreement> hostel_agreement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hostel_contract> hostel_contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hostel_manual_agreement> hostel_manual_agreement { get; set; }
    }
}
