//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class gal_chief
    {
        public byte[] cdepartment { get; set; }
        public byte[] cperson { get; set; }
        public Nullable<int> isChief { get; set; }
        public int id { get; set; }
    }
}
