//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class hostel_debt_payment
    {
        public int id { get; set; }
        public int hcid { get; set; }
        public decimal debt { get; set; }
    
        public virtual hostel_contract hostel_contract { get; set; }
    }
}
