//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class hostel_manual_agreement
    {
        public int id { get; set; }
        public int fnpp { get; set; }
        public string student { get; set; }
        public string gal_order { get; set; }
        public int hcostid { get; set; }
        public int agrType { get; set; }
        public Nullable<System.DateTime> agrBegin { get; set; }
        public Nullable<System.DateTime> agrEnd { get; set; }
        public string order { get; set; }
        public string filename { get; set; }
    
        public virtual fdata fdata { get; set; }
        public virtual hostel_catalog hostel_catalog { get; set; }
        public virtual hostel_cost hostel_cost { get; set; }
    }
}
