//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class hostel_contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hostel_contract()
        {
            this.hostel_agreement = new HashSet<hostel_agreement>();
            this.hostel_debt_payment = new HashSet<hostel_debt_payment>();
        }
    
        public int id { get; set; }
        public int fnpp { get; set; }
        public string student { get; set; }
        public string contNumber { get; set; }
        public System.DateTime contDate { get; set; }
        public int contType { get; set; }
        public string order { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public System.DateTime contBegin { get; set; }
        public System.DateTime contEnd { get; set; }
        public Nullable<System.DateTime> factLivBegDate { get; set; }
        public Nullable<System.DateTime> factLivEndDate { get; set; }
        public int housingId { get; set; }
        public int hcostid { get; set; }
        public Nullable<decimal> costTotal { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> change { get; set; }
        public string reason { get; set; }
        public string filename { get; set; }
        public string filenameRVP { get; set; }
        public string ulivNrec { get; set; }
        public Nullable<int> isPopulate { get; set; }
        public Nullable<System.DateTime> dateConfirmPopulate { get; set; }
    
        public virtual fdata fdata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hostel_agreement> hostel_agreement { get; set; }
        public virtual hostel_catalog hostel_catalog { get; set; }
        public virtual hostel_cost hostel_cost { get; set; }
        public virtual hostel_housing hostel_housing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hostel_debt_payment> hostel_debt_payment { get; set; }
    }
}
