//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class keylinks
    {
        public int npp { get; set; }
        public Nullable<int> fnpp { get; set; }
        public string lotus_unid { get; set; }
        public Nullable<System.Guid> C1c_unid { get; set; }
        public byte[] gal_unid { get; set; }
        public string passprom { get; set; }
        public string userprom { get; set; }
        public string bitrix_unid { get; set; }
        public Nullable<int> fvalidator { get; set; }
        public Nullable<bool> valid { get; set; }
        public Nullable<System.DateTime> dv { get; set; }
        public string wlotus_unid { get; set; }
        public string adpass { get; set; }
        public string adname { get; set; }
        public string adphone { get; set; }
        public Nullable<System.DateTime> addc { get; set; }
        public Nullable<bool> role { get; set; }
        public Nullable<System.Guid> C1c_unid_rp { get; set; }
    
        public virtual fdata fdata { get; set; }
    }
}
