//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text;
using SFAA.Entities;

namespace SFAA.DBAdapter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;

    public partial class OMGTU810Entities : DbContext
    {
        public OMGTU810Entities()
            : base(GetConnectionString())
        {
        }


        private static string GetConnectionString()
        {
            string st1 = @"metadata=res://*/OMGTU810DBModel.csdl|res://*/OMGTU810DBModel.ssdl|res://*/OMGTU810DBModel.msl;provider=System.Data.SqlClient;provider connection string='data source=";
            string st2 = GlobalSettings.Instance.DnsGal;
            string st3 = ";initial catalog=";
            string st4 = GlobalSettings.Instance.GalDb;
            string st5 = ";persist security info=True;user id=";
            string st6 = GlobalSettings.Instance.AuthDataGalLogin;
            string st7 = ";password=";
            string st8 = GlobalSettings.Instance.AuthDataGalPass;
            string st9 = ";MultipleActiveResultSets=True;App=EntityFramework'";

            return string.Concat(st1, st2, st3, st4, st5, st6, st7, st8, st9);
        }

        public virtual DbSet<T_UP_WRATING> T_UP_WRATING { get; set; }
        public virtual DbSet<T_UP_WRATING_HOURS> T_UP_WRATING_HOURS { get; set; }
        public virtual DbSet<T_ATTRVAL> T_ATTRVAL { get; set; }
        public virtual DbSet<T_CATALOGS> T_CATALOGS { get; set; }
        public virtual DbSet<T_DOPINFO> T_DOPINFO { get; set; }
        public virtual DbSet<T_PERSONS> T_PERSONS { get; set; }
        public virtual DbSet<T_U_CURRICULUM> T_U_CURRICULUM { get; set; }
        public virtual DbSet<T_U_DB_DIPLOMA> T_U_DB_DIPLOMA { get; set; }
        public virtual DbSet<T_U_DISCIPLINE> T_U_DISCIPLINE { get; set; }
        public virtual DbSet<T_U_LIST> T_U_LIST { get; set; }
        public virtual DbSet<T_U_LIST_EXAMINER> T_U_LIST_EXAMINER { get; set; }
        public virtual DbSet<T_U_MARKS> T_U_MARKS { get; set; }
        public virtual DbSet<T_U_STUDENT> T_U_STUDENT { get; set; }
        public virtual DbSet<T_U_STUDGROUP> T_U_STUDGROUP { get; set; }
        public virtual DbSet<T_U_TYPEWORK> T_U_TYPEWORK { get; set; }
        public virtual DbSet<T_U_TOLERANCESESSION> T_U_TOLERANCESESSION { get; set; }
        public virtual DbSet<T_APPOINTMENTS> T_APPOINTMENTS { get; set; }
        public virtual DbSet<T_CONTDOC> T_CONTDOC { get; set; }
        public virtual DbSet<T_PARTDOC> T_PARTDOC { get; set; }
        public virtual DbSet<T_TITLEDOC> T_TITLEDOC { get; set; }
        public virtual DbSet<T_U_CURR_DIS_STUDTRANS> T_U_CURR_DIS_STUDTRANS { get; set; }
        public virtual DbSet<T_EDUCATION> T_EDUCATION { get; set; }
    }
}
