//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studbaseEntities : DbContext
    {
        public studbaseEntities()
            : base("name=studbaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fdata> fdata { get; set; }
        public virtual DbSet<keylinks> keylinks { get; set; }
        public virtual DbSet<skard> skard { get; set; }
        public virtual DbSet<struct_d_rp> struct_d_rp { get; set; }
        public virtual DbSet<wkardc_rp> wkardc_rp { get; set; }
        public virtual DbSet<hostel_agreement> hostel_agreement { get; set; }
        public virtual DbSet<hostel_catalog> hostel_catalog { get; set; }
        public virtual DbSet<hostel_contract> hostel_contract { get; set; }
        public virtual DbSet<hostel_cost> hostel_cost { get; set; }
        public virtual DbSet<hostel_cost_calculation> hostel_cost_calculation { get; set; }
        public virtual DbSet<hostel_cost_order> hostel_cost_order { get; set; }
        public virtual DbSet<hostel_debt_payment> hostel_debt_payment { get; set; }
        public virtual DbSet<hostel_housing> hostel_housing { get; set; }
        public virtual DbSet<hostel_manual_agreement> hostel_manual_agreement { get; set; }
        public virtual DbSet<hostel_settings> hostel_settings { get; set; }
        public virtual DbSet<gal_chief> gal_chief { get; set; }
    }
}
