//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class skard
    {
        public int npp { get; set; }
        public Nullable<int> fnpp { get; set; }
        public string prudal { get; set; }
        public string gruppa { get; set; }
        public string fak { get; set; }
        public string spec { get; set; }
        public string form { get; set; }
        public string fin { get; set; }
        public Nullable<System.DateTime> du { get; set; }
        public Nullable<System.DateTime> dr { get; set; }
        public string user { get; set; }
        public Nullable<int> kurs { get; set; }
        public Nullable<int> contract { get; set; }
        public Nullable<int> ytransf { get; set; }
        public Nullable<int> ustate { get; set; }
        public Nullable<int> ifak { get; set; }
        public Nullable<int> iform { get; set; }
        public Nullable<int> ifin { get; set; }
        public Nullable<int> ispec { get; set; }
        public Nullable<int> knpp { get; set; }
        public Nullable<int> zorder { get; set; }
        public string qualif { get; set; }
        public Nullable<int> iqualif { get; set; }
        public string gal_chair { get; set; }
        public string gal_group { get; set; }
        public string gal_faculty { get; set; }
        public string gal_nation { get; set; }
        public string gal_specname { get; set; }
        public string gal_speccode { get; set; }
        public Nullable<System.DateTime> dr_gal { get; set; }
        public Nullable<System.DateTime> dr_lot { get; set; }
        public byte[] gal_srec { get; set; }
        public Nullable<int> ikaf { get; set; }
        public byte[] gal_UP { get; set; }
        public Nullable<bool> todel { get; set; }
        public Nullable<int> ispecialize { get; set; }
        public Nullable<int> itarget { get; set; }
        public Nullable<int> itargetdetail { get; set; }
        public Nullable<System.DateTime> dn { get; set; }
        public Nullable<System.DateTime> dno { get; set; }
    }
}
