//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class struct_d_rp
    {
        public int npp { get; set; }
        public Nullable<int> pnpp { get; set; }
        public string name { get; set; }
        public Nullable<int> l { get; set; }
        public Nullable<int> r { get; set; }
        public Nullable<int> u { get; set; }
        public string guid { get; set; }
        public Nullable<System.DateTime> cd { get; set; }
        public Nullable<System.DateTime> dd { get; set; }
        public Nullable<System.DateTime> dr { get; set; }
        public string code { get; set; }
        public Nullable<int> prudal { get; set; }
        public string head { get; set; }
        public Nullable<bool> composed { get; set; }
        public Nullable<bool> decomposed { get; set; }
        public string ikafcode { get; set; }
    }
}
