//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_APPOINTMENTS
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_LASTUSER { get; set; }
        public int F_LASTTIME { get; set; }
        public int F_LASTDATE { get; set; }
        public int F_FILIALNO { get; set; }
        public byte[] F_PERSON { get; set; }
        public int F_ORDERDATE { get; set; }
        public string F_ORDERNMB { get; set; }
        public byte[] F_CCONT { get; set; }
        public string F_CONTRACTNMB { get; set; }
        public int F_CONTRACTDATE { get; set; }
        public int F_DATEEND { get; set; }
        public int F_APPOINTDATE { get; set; }
        public int F_DISMISSDATE { get; set; }
        public byte[] F_DEPARTMENT { get; set; }
        public byte[] F_POST { get; set; }
        public byte[] F_TARIFF { get; set; }
        public int F_CATEGORY { get; set; }
        public byte[] F_EMPCATEGORY { get; set; }
        public int F_PAYMODEL { get; set; }
        public byte[] F_WORKCOND { get; set; }
        public byte[] F_POSTACCORD { get; set; }
        public byte[] F_WORKREGIME { get; set; }
        public decimal F_TAXRATE { get; set; }
        public byte[] F_PAYCURRENCY { get; set; }
        public byte[] F_PRIVPENSION { get; set; }
        public double F_EMPRATE { get; set; }
        public short F_VACATION { get; set; }
        public string F_FOUNDATION { get; set; }
        public byte[] F_TYPEMOVE { get; set; }
        public byte[] F_STAFFSTR { get; set; }
        public double F_RATE { get; set; }
        public short F_STATUSAPP { get; set; }
        public byte[] F_KINDAPP { get; set; }
        public byte[] F_CADDNREC1 { get; set; }
        public byte[] F_CADDNREC2 { get; set; }
        public int F_DADDDATE1 { get; set; }
        public int F_WADDWORD1 { get; set; }
        public int F_APPTABNMB { get; set; }
        public short F_LPRIZN { get; set; }
        public byte[] F_CDOG { get; set; }
        public string F_NMBDOG { get; set; }
        public int F_WPRIZN { get; set; }
        public byte[] F_CDOPINF { get; set; }
        public byte[] F_CREF1 { get; set; }
        public byte[] F_CREF2 { get; set; }
        public byte[] F_CREF3 { get; set; }
        public byte[] F_CORG { get; set; }
        public byte[] F_CCAT1 { get; set; }
        public byte[] F_CCAT2 { get; set; }
        public int F_DDOP1 { get; set; }
        public int F_DDOP2 { get; set; }
        public double F_COEF1 { get; set; }
        public double F_COEF2 { get; set; }
        public double F_RSUM { get; set; }
        public byte[] F_OLDCLSCH { get; set; }
        public string F_STRTABN { get; set; }
        public double F_RSUM1 { get; set; }
        public double F_RSUM2 { get; set; }
        public double F_RSUM3 { get; set; }
        public byte[] F_CDOPADR { get; set; }
        public byte[] F_CDOPOKATO { get; set; }
        public byte[] F_CDOPPODR { get; set; }
        public byte[] F_CDOPNI { get; set; }
        public int F_RESWORD_1_ { get; set; }
        public int F_RESWORD_2_ { get; set; }
        public int F_RESWORD_3_ { get; set; }
        public int F_RESWORD_4_ { get; set; }
        public int F_RESWORD_5_ { get; set; }
        public int F_RESWORD_6_ { get; set; }
        public int F_RESWORD_7_ { get; set; }
        public int F_RESWORD_8_ { get; set; }
        public int F_RESWORD_9_ { get; set; }
        public int F_RESWORD_10_ { get; set; }
        public int F_RESWORD_11_ { get; set; }
        public int F_RESWORD_12_ { get; set; }
        public int F_RESWORD_13_ { get; set; }
        public int F_RESWORD_14_ { get; set; }
        public int F_RESWORD_15_ { get; set; }
        public int F_RESWORD_16_ { get; set; }
        public int F_RESWORD_17_ { get; set; }
        public int F_RESWORD_18_ { get; set; }
        public int F_RESWORD_19_ { get; set; }
        public int F_RESWORD_20_ { get; set; }
        public byte[] F_RESCOMP_1_ { get; set; }
        public byte[] F_RESCOMP_2_ { get; set; }
        public byte[] F_RESCOMP_3_ { get; set; }
        public byte[] F_RESCOMP_4_ { get; set; }
        public byte[] F_RESCOMP_5_ { get; set; }
        public byte[] F_RESCOMP_6_ { get; set; }
        public byte[] F_RESCOMP_7_ { get; set; }
        public byte[] F_RESCOMP_8_ { get; set; }
        public byte[] F_RESCOMP_9_ { get; set; }
        public byte[] F_RESCOMP_10_ { get; set; }
        public decimal F_RESDOUBLE_1_ { get; set; }
        public decimal F_RESDOUBLE_2_ { get; set; }
        public decimal F_RESDOUBLE_3_ { get; set; }
        public decimal F_RESDOUBLE_4_ { get; set; }
        public decimal F_RESDOUBLE_5_ { get; set; }
        public decimal F_RESDOUBLE_6_ { get; set; }
        public byte[] F_CWRKTYPE { get; set; }
        public byte[] F_CDISDASIS { get; set; }
        public byte[] F_CDISREASON { get; set; }
        public string F_SRESOLUTIONNMB { get; set; }
        public int F_DRESOLUTIONDATE { get; set; }
        public int F_DORDERDISDATE { get; set; }
    }
}
