//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ATTRVAL
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public string F_LASTUSER { get; set; }
        public int F_LASTTIME { get; set; }
        public int F_LASTDATE { get; set; }
        public int F_FILIALNO { get; set; }
        public int F_WTABLE { get; set; }
        public byte[] F_CREC { get; set; }
        public byte[] F_CATTRNAM { get; set; }
        public string F_VSTRING { get; set; }
        public double F_VDOUBLE { get; set; }
        public int F_VDATE { get; set; }
        public int F_VTIME { get; set; }
        public byte[] F_VCOMP { get; set; }
        public bool F_VLVAR { get; set; }
        public int F_VLONGINT { get; set; }
    }
}
