//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CATALOGS
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_LASTUSER { get; set; }
        public int F_LASTTIME { get; set; }
        public int F_LASTDATE { get; set; }
        public int F_FILIALNO { get; set; }
        public byte[] F_CPARENT { get; set; }
        public short F_GROUPCODE { get; set; }
        public short F_SYSCODE { get; set; }
        public string F_ADDINF { get; set; }
        public string F_NAME { get; set; }
        public string F_CODE { get; set; }
        public string F_CATDATA { get; set; }
        public byte[] F_MAINLINK { get; set; }
        public short F_LPR { get; set; }
        public int F_BMULTI { get; set; }
        public int F_BPICK { get; set; }
        public int F_ISLEAF { get; set; }
        public byte[] F_CREF { get; set; }
        public int F_DATN { get; set; }
        public int F_DATOK { get; set; }
        public string F_SDOPINF { get; set; }
        public byte[] F_CREF1 { get; set; }
        public byte[] F_CREF2 { get; set; }
        public byte[] F_CREF3 { get; set; }
        public int F_WKOD { get; set; }
        public int F_DAT1 { get; set; }
        public int F_DAT2 { get; set; }
        public string F_DOPSTR { get; set; }
        public string F_LONGNAME { get; set; }
    }
}
