//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONTDOC
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_LASTUSER { get; set; }
        public int F_LASTTIME { get; set; }
        public int F_LASTDATE { get; set; }
        public int F_FILIALNO { get; set; }
        public byte[] F_CPART { get; set; }
        public int F_WREC { get; set; }
        public short F_NUMPART { get; set; }
        public string F_SBOTTOM { get; set; }
        public short F_TYPEOPER { get; set; }
        public byte[] F_PERSON { get; set; }
        public byte[] F_CSTR { get; set; }
        public short F_OBJTYPE { get; set; }
        public byte[] F_OBJNREC { get; set; }
        public short F_SEQNMB { get; set; }
        public byte[] F_CDOPREF { get; set; }
        public int F_WDOP { get; set; }
        public byte[] F_CREF1 { get; set; }
        public byte[] F_CADDINF { get; set; }
        public byte[] F_CINF { get; set; }
        public int F_WDOPATTR { get; set; }
        public byte[] F_CNEWINF { get; set; }
        public byte[] F_CREZERV { get; set; }
        public byte[] F_CNEW1 { get; set; }
        public byte[] F_CNEW2 { get; set; }
        public byte[] F_CNEW3 { get; set; }
        public int F_WATTRDOC1 { get; set; }
        public int F_WATTRDOC2 { get; set; }
        public int F_DAT1 { get; set; }
        public int F_DAT2 { get; set; }
        public int F_DPRIK { get; set; }
        public int F_WYEARPR { get; set; }
        public int F_WORDER { get; set; }
        public byte[] F_CCAT1 { get; set; }
        public byte[] F_CCAT2 { get; set; }
        public int F_DREZERVE { get; set; }
        public byte[] F_CWORKPERIOD { get; set; }
        public int F_DDISDATE { get; set; }
        public byte[] F_CDISBASIC { get; set; }
        public byte[] F_CDISREASON { get; set; }
        public int F_LITABN { get; set; }
        public string F_STTABN { get; set; }
        public byte[] F_CNEW4 { get; set; }
        public byte[] F_CNEW5 { get; set; }
        public byte[] F_CNEW6 { get; set; }
        public byte[] F_CNEW7 { get; set; }
        public int F_WATTRDOC3 { get; set; }
        public int F_WATTRDOC4 { get; set; }
    }
}
