//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DOPINFO
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_LASTUSER { get; set; }
        public int F_LASTTIME { get; set; }
        public int F_LASTDATE { get; set; }
        public int F_FILIALNO { get; set; }
        public byte[] F_CDOPTBL { get; set; }
        public byte[] F_CPERSON { get; set; }
        public byte[] F_CFLD_1_ { get; set; }
        public byte[] F_CFLD_2_ { get; set; }
        public byte[] F_CFLD_3_ { get; set; }
        public byte[] F_CFLD_4_ { get; set; }
        public byte[] F_CFLD_5_ { get; set; }
        public byte F_BFLD_1_ { get; set; }
        public byte F_BFLD_2_ { get; set; }
        public byte F_BFLD_3_ { get; set; }
        public byte F_BFLD_4_ { get; set; }
        public byte F_BFLD_5_ { get; set; }
        public decimal F_FFLDSUM_1_ { get; set; }
        public decimal F_FFLDSUM_2_ { get; set; }
        public decimal F_FFLDSUM_3_ { get; set; }
        public decimal F_FFLDSUM_4_ { get; set; }
        public decimal F_FFLDSUM_5_ { get; set; }
        public string F_SFLD_1_ { get; set; }
        public string F_SFLD_2_ { get; set; }
        public string F_SFLD_3_ { get; set; }
        public string F_SFLD_4_ { get; set; }
        public string F_SFLD_5_ { get; set; }
        public int F_DFLD_1_ { get; set; }
        public int F_DFLD_2_ { get; set; }
        public int F_DFLD_3_ { get; set; }
        public int F_DFLD_4_ { get; set; }
        public int F_DFLD_5_ { get; set; }
    }
}
