//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EDUCATION
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_LASTUSER { get; set; }
        public int F_LASTTIME { get; set; }
        public int F_LASTDATE { get; set; }
        public int F_FILIALNO { get; set; }
        public byte[] F_PERSON { get; set; }
        public byte[] F_LEVEL { get; set; }
        public byte[] F_NAME { get; set; }
        public byte[] F_LEARNADDR { get; set; }
        public byte[] F_MODE { get; set; }
        public short F_COURSE { get; set; }
        public int F_FROMDATE { get; set; }
        public int F_TODATE { get; set; }
        public string F_DIPLOMNMB { get; set; }
        public int F_DIPLOMDATE { get; set; }
        public byte[] F_SPECIALITY { get; set; }
        public byte[] F_QUALIFICATION { get; set; }
        public short F_SEQNMB { get; set; }
        public byte[] F_CQUALTYPE { get; set; }
        public byte[] F_CREASON { get; set; }
        public string F_SNOTE { get; set; }
        public byte[] F_CADDINF1 { get; set; }
        public int F_WDOP { get; set; }
        public short F_IATTR { get; set; }
        public int F_WTYPE { get; set; }
        public decimal F_PAYSUM { get; set; }
        public byte[] F_CINF1 { get; set; }
        public byte[] F_CINF2 { get; set; }
        public byte[] F_CPLACE { get; set; }
        public byte[] F_CCONTDOC { get; set; }
        public short F_IDOP { get; set; }
        public int F_DPLAN1 { get; set; }
        public int F_DPLAN2 { get; set; }
        public int F_WREZ { get; set; }
        public byte[] F_CREF1 { get; set; }
        public byte[] F_CREF2 { get; set; }
        public int F_WCODE { get; set; }
        public string F_SERIES { get; set; }
        public int F_DAT_1 { get; set; }
        public int F_DAT_2 { get; set; }
        public short F_NMB1 { get; set; }
        public short F_NMB2 { get; set; }
        public string F_STR1 { get; set; }
        public string F_STR2 { get; set; }
        public byte[] F_CDIRECT { get; set; }
    }
}
