//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PARTDOC
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_LASTUSER { get; set; }
        public int F_LASTTIME { get; set; }
        public int F_LASTDATE { get; set; }
        public int F_FILIALNO { get; set; }
        public byte[] F_CDOC { get; set; }
        public short F_TYPEOPER { get; set; }
        public int F_NRAZD { get; set; }
        public byte[] F_PARTMEMO { get; set; }
        public byte[] F_CMEMO { get; set; }
        public int F_ISPERS { get; set; }
        public byte[] F_CPREF { get; set; }
        public int F_WATTR { get; set; }
        public byte[] F_CREF1 { get; set; }
        public byte[] F_CREF2 { get; set; }
        public int F_WATTR1 { get; set; }
        public int F_WATTR2 { get; set; }
        public byte[] F_CPODR { get; set; }
        public byte[] F_CCAT { get; set; }
        public int F_DDAT1 { get; set; }
        public int F_DDAT2 { get; set; }
        public int F_WINF1 { get; set; }
        public int F_WINF2 { get; set; }
    }
}
