//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PERSONS
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_LASTUSER { get; set; }
        public int F_LASTTIME { get; set; }
        public int F_LASTDATE { get; set; }
        public int F_FILIALNO { get; set; }
        public string F_FIO { get; set; }
        public int F_BORNDATE { get; set; }
        public byte[] F_BORNADDR { get; set; }
        public int F_DEPENDANTS { get; set; }
        public string F_SEX { get; set; }
        public byte[] F_NATIONALITY { get; set; }
        public byte[] F_PASSPRUS { get; set; }
        public byte[] F_PASSPFOR { get; set; }
        public byte[] F_LIVEADDR { get; set; }
        public byte[] F_PASSPADDR { get; set; }
        public byte[] F_FAMILYSTATE { get; set; }
        public byte[] F_EDUCATION { get; set; }
        public short F_PUBLICATIONS { get; set; }
        public short F_INVENTIONS { get; set; }
        public string F_PASSNMB { get; set; }
        public byte[] F_DEPARTMENT { get; set; }
        public byte[] F_GALDEP { get; set; }
        public byte[] F_GALDEPHOST { get; set; }
        public int F_TABNMB { get; set; }
        public int F_TESTPERIOD { get; set; }
        public byte[] F_JOBNATURE { get; set; }
        public byte[] F_COMPLSRC { get; set; }
        public byte[] F_INVALIDGRP { get; set; }
        public int F_PENSIONDATE { get; set; }
        public byte[] F_PENSIONCAUSE { get; set; }
        public int F_DISORDERDATE { get; set; }
        public string F_DISORDERNMB { get; set; }
        public int F_DISDATE { get; set; }
        public byte[] F_DISREASON { get; set; }
        public byte[] F_DISMOTIVE { get; set; }
        public string F_DISPROFNMB { get; set; }
        public int F_DISPROFDATE { get; set; }
        public int F_APPDATE { get; set; }
        public byte[] F_APPOINTCUR { get; set; }
        public byte[] F_APPOINTFIRST { get; set; }
        public byte[] F_APPOINTLAST { get; set; }
        public string F_ISEMPLOYEE { get; set; }
        public int F_ISPERSBUH { get; set; }
        public byte[] F_GR { get; set; }
        public byte[] F_CSOVM { get; set; }
        public int F_DISDATEPR { get; set; }
        public byte[] F_CADDNREC1 { get; set; }
        public int F_DADDDATE1 { get; set; }
        public byte[] F_CADDNREC2 { get; set; }
        public int F_DADDDATE2 { get; set; }
        public int F_WADDWORD { get; set; }
        public byte[] F_CBASEPROF { get; set; }
        public byte[] F_CADDPROF { get; set; }
        public byte[] F_CDOPREF1 { get; set; }
        public byte[] F_CDOPREF2 { get; set; }
        public byte[] F_CDOPREF3 { get; set; }
        public int F_WPRIZN1 { get; set; }
        public int F_WPRIZN2 { get; set; }
        public int F_WPRIZN3 { get; set; }
        public int F_DDAT1 { get; set; }
        public int F_DDAT2 { get; set; }
        public short F_IATTR { get; set; }
        public byte[] F_CPRIZN1 { get; set; }
        public byte[] F_CPRIZN2 { get; set; }
        public byte[] F_CPRIZN3 { get; set; }
        public int F_WFEATURE1 { get; set; }
        public int F_WFEATURE2 { get; set; }
        public int F_DDOP1 { get; set; }
        public int F_DDOP2 { get; set; }
        public byte[] F_STRHOST { get; set; }
        public string F_STRTABN { get; set; }
        public string F_SFIOLAT { get; set; }
    }
}
