//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TITLEDOC
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_LASTUSER { get; set; }
        public int F_LASTTIME { get; set; }
        public int F_LASTDATE { get; set; }
        public int F_FILIALNO { get; set; }
        public string F_DOCNMB { get; set; }
        public short F_INMB { get; set; }
        public int F_DOCDATE { get; set; }
        public int F_DOCYEAR { get; set; }
        public int F_WSTATUS { get; set; }
        public int F_DOCTYPE { get; set; }
        public string F_DOCTEXT { get; set; }
        public byte[] F_DOCMEMO { get; set; }
        public int F_WTITL { get; set; }
        public byte[] F_CTITL { get; set; }
        public byte[] F_CINF { get; set; }
        public int F_WDOP { get; set; }
        public byte[] F_CINF1 { get; set; }
        public byte[] F_CINF2 { get; set; }
        public byte[] F_CINF3 { get; set; }
        public int F_WATTR { get; set; }
        public byte[] F_CATTR1 { get; set; }
        public byte[] F_CATTR2 { get; set; }
        public int F_DAT1 { get; set; }
        public int F_DAT2 { get; set; }
    }
}
