//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class T_U_LIST
    {
        public byte[] Sys_UL { get; set; }
        [Key]
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_DESCR { get; set; }
        public string F_DESGR { get; set; }
        public int F_WTYPE { get; set; }
        public byte[] F_CCUR { get; set; }
        public byte[] F_CDIS { get; set; }
        public int F_DATEMAKE { get; set; }
        public int F_DATEDOC { get; set; }
        public int F_WPERIOD { get; set; }
        public string F_NUMDOC { get; set; }
        public string F_BARCODE { get; set; }
        public int F_WFORMED { get; set; }
        public byte[] F_CFAC { get; set; }
        public byte[] F_CINSTITUT { get; set; }
        public byte[] F_CCHAIR { get; set; }
        public byte[] F_CEXAMINER { get; set; }
        public byte[] F_CSTGR { get; set; }
        public byte[] F_CPARENT { get; set; }
        public int F_WSEMESTR { get; set; }
        public int F_WTYPEDIFFER { get; set; }
        public int F_WSTATUS { get; set; }
        public int F_WHOURS { get; set; }
        public int F_WHOURSAUD { get; set; }
        public int F_INDIPLOM { get; set; }
        public int F_WYEARED { get; set; }
        public byte[] F_CTYPEWORK { get; set; }
        public int F_WADDFLD_1_ { get; set; }
        public int F_WADDFLD_2_ { get; set; }
        public int F_WADDFLD_3_ { get; set; }
        public int F_WADDFLD_4_ { get; set; }
        public int F_WADDFLD_5_ { get; set; }
        public int F_WADDFLD_6_ { get; set; }
        public int F_WADDFLD_7_ { get; set; }
        public int F_WADDFLD_8_ { get; set; }
        public int F_WADDFLD_9_ { get; set; }
        public int F_WADDFLD_10_ { get; set; }
        public byte[] F_CADDFLD_1_ { get; set; }
        public byte[] F_CADDFLD_2_ { get; set; }
        public byte[] F_CADDFLD_3_ { get; set; }
        public byte[] F_CADDFLD_4_ { get; set; }
        public byte[] F_CADDFLD_5_ { get; set; }
        public byte[] F_CADDFLD_6_ { get; set; }
        public byte[] F_CADDFLD_7_ { get; set; }
        public byte[] F_CADDFLD_8_ { get; set; }
        public byte[] F_CADDFLD_9_ { get; set; }
        public byte[] F_CADDFLD_10_ { get; set; }
        public decimal F_DADDFLD_1_ { get; set; }
        public decimal F_DADDFLD_2_ { get; set; }
        public decimal F_DADDFLD_3_ { get; set; }
        public decimal F_DADDFLD_4_ { get; set; }
        public decimal F_DADDFLD_5_ { get; set; }
        public decimal F_DADDFLD_6_ { get; set; }
        public decimal F_DADDFLD_7_ { get; set; }
        public decimal F_DADDFLD_8_ { get; set; }
        public decimal F_DADDFLD_9_ { get; set; }
        public decimal F_DADDFLD_10_ { get; set; }
        public string F_SADDFLD_1_ { get; set; }
        public string F_SADDFLD_2_ { get; set; }
        public string F_SADDFLD_3_ { get; set; }
        public string F_SADDFLD_4_ { get; set; }
        public string F_SADDFLD_5_ { get; set; }
        public string F_SADDFLD_6_ { get; set; }
        public string F_SADDFLD_7_ { get; set; }
        public string F_SADDFLD_8_ { get; set; }
        public string F_SADDFLD_9_ { get; set; }
        public string F_SADDFLD_10_ { get; set; }
    }
}
