//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_U_CURRICULUM
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_NAME { get; set; }
        public int F_WTYPE { get; set; }
        public byte[] F_CPARENT { get; set; }
        public byte[] F_CMODEL { get; set; }
        public byte[] F_CEDSTD { get; set; }
        public string F_DESCR { get; set; }
        public string F_DESGR { get; set; }
        public byte[] F_CNOTE { get; set; }
        public int F_STATUS { get; set; }
        public int F_WFORMED { get; set; }
        public double F_TERM { get; set; }
        public int F_DATEAPP { get; set; }
        public int F_DATEEND { get; set; }
        public string F_REGNUM { get; set; }
        public string F_SPECIALITYCODE { get; set; }
        public int F_YEARED { get; set; }
        public int F_COURSE { get; set; }
        public byte[] F_CQUALIFICATION { get; set; }
        public byte[] F_CSPECIALITY { get; set; }
        public byte[] F_CSPECIALIZATION { get; set; }
        public byte[] F_CFACULTY { get; set; }
        public byte[] F_CINSTITUT { get; set; }
        public byte[] F_CCHAIR { get; set; }
        public byte[] F_CBASEEDUCATION { get; set; }
        public int F_NUMSTUD { get; set; }
        public int F_NUMSTUDLOAD { get; set; }
        public int F_HOURGOSPLAN { get; set; }
        public double F_DCREDITGOSPLAN { get; set; }
        public int F_HOURCURPLAN { get; set; }
        public double F_DCREDITCURPLAN { get; set; }
        public int F_HOURLECROOM { get; set; }
        public int F_HOURSTUDOWN { get; set; }
        public int F_HOURCONTOWN { get; set; }
        public int F_HOUREXAM { get; set; }
        public int F_NUMEXAM { get; set; }
        public int F_NUMTEST { get; set; }
        public double F_CREDLECROOM { get; set; }
        public double F_CREDSTUDOWN { get; set; }
        public double F_CREDCONTOWN { get; set; }
        public double F_CREDEXAM { get; set; }
        public double F_CREDTEST { get; set; }
        public double F_CREDPRJ { get; set; }
        public double F_CREDWRK { get; set; }
        public double F_CREDCTR { get; set; }
        public int F_WADDFLD_1_ { get; set; }
        public int F_WADDFLD_2_ { get; set; }
        public int F_WADDFLD_3_ { get; set; }
        public int F_WADDFLD_4_ { get; set; }
        public int F_WADDFLD_5_ { get; set; }
        public int F_WADDFLD_6_ { get; set; }
        public int F_WADDFLD_7_ { get; set; }
        public int F_WADDFLD_8_ { get; set; }
        public int F_WADDFLD_9_ { get; set; }
        public int F_WADDFLD_10_ { get; set; }
        public byte[] F_CADDFLD_1_ { get; set; }
        public byte[] F_CADDFLD_2_ { get; set; }
        public byte[] F_CADDFLD_3_ { get; set; }
        public byte[] F_CADDFLD_4_ { get; set; }
        public byte[] F_CADDFLD_5_ { get; set; }
        public byte[] F_CADDFLD_6_ { get; set; }
        public byte[] F_CADDFLD_7_ { get; set; }
        public byte[] F_CADDFLD_8_ { get; set; }
        public byte[] F_CADDFLD_9_ { get; set; }
        public byte[] F_CADDFLD_10_ { get; set; }
        public decimal F_DADDFLD_1_ { get; set; }
        public decimal F_DADDFLD_2_ { get; set; }
        public decimal F_DADDFLD_3_ { get; set; }
        public decimal F_DADDFLD_4_ { get; set; }
        public decimal F_DADDFLD_5_ { get; set; }
        public decimal F_DADDFLD_6_ { get; set; }
        public decimal F_DADDFLD_7_ { get; set; }
        public decimal F_DADDFLD_8_ { get; set; }
        public decimal F_DADDFLD_9_ { get; set; }
        public decimal F_DADDFLD_10_ { get; set; }
        public string F_SADDFLD_1_ { get; set; }
        public string F_SADDFLD_2_ { get; set; }
        public string F_SADDFLD_3_ { get; set; }
        public string F_SADDFLD_4_ { get; set; }
        public string F_SADDFLD_5_ { get; set; }
        public string F_SADDFLD_6_ { get; set; }
        public string F_SADDFLD_7_ { get; set; }
        public string F_SADDFLD_8_ { get; set; }
        public string F_SADDFLD_9_ { get; set; }
        public string F_SADDFLD_10_ { get; set; }
        public int F_WGOS { get; set; }
        public int F_WDEGREE { get; set; }
        public double F_DCREDEQUIVAL { get; set; }
        public double F_DCREDCAPACITY { get; set; }
        public int F_WSHOT { get; set; }
        public int F_REATTSIZE { get; set; }
        public double F_REATTCREDSIZE { get; set; }
        public int F_WMODULEMODE { get; set; }
        public int F_WPROPERTIES { get; set; }
        public int F_WTYPEEDSCHED { get; set; }
        public int F_WMONTH { get; set; }
        public int F_HOURCONTWRK { get; set; }
        public double F_CREDCONTWRK { get; set; }
        public int F_WWEEK { get; set; }
        public bool F_INFO { get; set; }
        public int F_WADDFLD2_1_ { get; set; }
        public int F_WADDFLD2_2_ { get; set; }
        public int F_WADDFLD2_3_ { get; set; }
        public int F_WADDFLD2_4_ { get; set; }
        public int F_WADDFLD2_5_ { get; set; }
        public int F_WADDFLD2_6_ { get; set; }
        public int F_WADDFLD2_7_ { get; set; }
        public int F_WADDFLD2_8_ { get; set; }
        public int F_WADDFLD2_9_ { get; set; }
        public int F_WADDFLD2_10_ { get; set; }
    }
}
