//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_U_CURR_DIS_STUDTRANS
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_LASTUSER { get; set; }
        public int F_LASTTIME { get; set; }
        public int F_LASTDATE { get; set; }
        public int F_FILIALNO { get; set; }
        public byte[] F_CSTUD { get; set; }
        public byte[] F_CCURR { get; set; }
        public byte[] F_CCURR_DIS { get; set; }
        public byte[] F_CDIS { get; set; }
        public byte[] F_CSEM { get; set; }
        public int F_WSEM { get; set; }
        public byte[] F_CTYPEWORK { get; set; }
        public int F_WHOURS { get; set; }
        public int F_WHOURSAUD { get; set; }
        public int F_WRESIT { get; set; }
        public short F_WMARK { get; set; }
        public byte[] F_CMARK { get; set; }
        public int F_DDATEBEFORE { get; set; }
        public int F_DDATEMARK { get; set; }
        public string F_SNAME { get; set; }
        public byte[] F_CLIST { get; set; }
        public byte[] F_CCONTDOC { get; set; }
        public byte[] F_CCURR_STUDTRANS { get; set; }
        public int F_WTYPETRANS { get; set; }
        public byte[] F_CADDFLD { get; set; }
        public int F_WADDFLD { get; set; }
        public string F_SADDFLD { get; set; }
        public int F_DADDFLD { get; set; }
        public byte[] F_CLISTPREV { get; set; }
        public int F_INDIPLOM { get; set; }
    }
}
