//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_U_STUDGROUP
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_NAME { get; set; }
        public string F_EXTNAME { get; set; }
        public string F_NUMBER { get; set; }
        public int F_YEARENT { get; set; }
        public int F_YEARED { get; set; }
        public int F_COURSE { get; set; }
        public byte[] F_CFACULTY { get; set; }
        public byte[] F_CINSTITUT { get; set; }
        public byte[] F_CCHAIR { get; set; }
        public int F_NUMSTUD { get; set; }
        public int F_NUMSTUDFACT { get; set; }
        public byte[] F_CSP_G_RAB { get; set; }
        public int F_WFORMED { get; set; }
        public int F_WSTATUSGR { get; set; }
        public byte[] F_CSPEC { get; set; }
        public byte[] F_CQUALIFICATION { get; set; }
        public int F_NUMORDER { get; set; }
        public string F_SDOPINFO { get; set; }
        public int F_WKOLSTUDINRPD { get; set; }
        public string F_OLDNAME { get; set; }
        public byte[] F_CSPECIALIZATION { get; set; }
    }
}
