//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_U_STUDENT
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public byte[] F_CPERSONS { get; set; }
        public string F_FIO { get; set; }
        public string F_UNS { get; set; }
        public byte[] F_CSTGR { get; set; }
        public byte[] F_DEPARTMENT { get; set; }
        public int F_APPDATE { get; set; }
        public string F_SDEPCODE { get; set; }
        public string F_SDEPARTMENT { get; set; }
        public byte[] F_CPOST { get; set; }
        public string F_SPOST { get; set; }
        public string F_CODEPROF { get; set; }
        public byte[] F_CEDUCATION { get; set; }
        public int F_DISDATE { get; set; }
        public byte[] F_CCURR { get; set; }
        public int F_WARCH { get; set; }
        public int F_WFORMED { get; set; }
        public string F_SFINSOURCENAME { get; set; }
        public byte[] F_CFINSOURCENAME { get; set; }
        public string F_SFACULTY { get; set; }
        public byte[] F_CFACULTY { get; set; }
        public byte[] F_CINSTITUT { get; set; }
        public int F_WTRANSFER { get; set; }
        public byte[] F_CPAIDCATEGORY { get; set; }
        public int F_WOTPUSK { get; set; }
        public byte[] F_CKATEG { get; set; }
        public string F_SKATEG { get; set; }
        public byte[] F_CQUALIFICATION { get; set; }
        public byte[] F_CSTATUS { get; set; }
        public string F_SSTATUS { get; set; }
        public int F_WTYPE { get; set; }
        public byte[] F_CDEANOFFICE { get; set; }
        public int F_WCOURSE { get; set; }
        public int F_WDEGREE { get; set; }
        public string F_SDEGREE { get; set; }
        public byte[] F_CFOREIGNCAT { get; set; }
        public int F_WSTYDYPROGRAM { get; set; }
        public int F_WTRANSFERCOND { get; set; }
        public string F_BARCODE { get; set; }
        public string F_BARCODEP { get; set; }
    }
}
