//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_U_DISCIPLINE
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_NAME { get; set; }
        public string F_CODE { get; set; }
        public string F_ABBR { get; set; }
        public byte[] F_CCHAIR { get; set; }
        public byte[] F_CCYCLE { get; set; }
        public int F_WPHYSCULTUR { get; set; }
        public int F_WTYPE { get; set; }
        public int F_WCREDCOUNT { get; set; }
        public byte[] F_CCATLANG { get; set; }
        public int F_WPROPERTIES { get; set; }
        public byte[] F_CPRACTTYPE { get; set; }
    }
}
