//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_U_DB_DIPLOMA
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_DESCR { get; set; }
        public string F_DESGR { get; set; }
        public int F_WTYPEDOC { get; set; }
        public string F_SNAME { get; set; }
        public int F_DDATEDOC { get; set; }
        public byte[] F_CAUTHOR { get; set; }
        public byte[] F_CTEACHER { get; set; }
        public byte[] F_CCRITIC { get; set; }
        public byte[] F_CDIS { get; set; }
        public int F_WADDFLD_1_ { get; set; }
        public int F_WADDFLD_2_ { get; set; }
        public int F_WADDFLD_3_ { get; set; }
        public int F_WADDFLD_4_ { get; set; }
        public int F_WADDFLD_5_ { get; set; }
        public int F_WADDFLD_6_ { get; set; }
        public int F_WADDFLD_7_ { get; set; }
        public int F_WADDFLD_8_ { get; set; }
        public int F_WADDFLD_9_ { get; set; }
        public int F_WADDFLD_10_ { get; set; }
        public byte[] F_CADDFLD_1_ { get; set; }
        public byte[] F_CADDFLD_2_ { get; set; }
        public byte[] F_CADDFLD_3_ { get; set; }
        public byte[] F_CADDFLD_4_ { get; set; }
        public byte[] F_CADDFLD_5_ { get; set; }
        public byte[] F_CADDFLD_6_ { get; set; }
        public byte[] F_CADDFLD_7_ { get; set; }
        public byte[] F_CADDFLD_8_ { get; set; }
        public byte[] F_CADDFLD_9_ { get; set; }
        public byte[] F_CADDFLD_10_ { get; set; }
        public decimal F_DADDFLD_1_ { get; set; }
        public decimal F_DADDFLD_2_ { get; set; }
        public decimal F_DADDFLD_3_ { get; set; }
        public decimal F_DADDFLD_4_ { get; set; }
        public decimal F_DADDFLD_5_ { get; set; }
        public decimal F_DADDFLD_6_ { get; set; }
        public decimal F_DADDFLD_7_ { get; set; }
        public decimal F_DADDFLD_8_ { get; set; }
        public decimal F_DADDFLD_9_ { get; set; }
        public decimal F_DADDFLD_10_ { get; set; }
        public string F_SADDFLD_1_ { get; set; }
        public string F_SADDFLD_2_ { get; set; }
        public string F_SADDFLD_3_ { get; set; }
        public string F_SADDFLD_4_ { get; set; }
        public string F_SADDFLD_5_ { get; set; }
        public string F_SADDFLD_6_ { get; set; }
        public string F_SADDFLD_7_ { get; set; }
        public string F_SADDFLD_8_ { get; set; }
        public string F_SADDFLD_9_ { get; set; }
        public string F_SADDFLD_10_ { get; set; }
        public string F_SNAME2 { get; set; }
    }
}
