//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_U_TYPEWORK
    {
        public byte[] Sys_UL { get; set; }
        public byte[] F_NREC { get; set; }
        public int F_ATL_LASTDATE { get; set; }
        public int F_ATL_LASTTIME { get; set; }
        public byte[] F_ATL_LASTUSER { get; set; }
        public int F_ATL_ORIGINOFFICE { get; set; }
        public byte[] F_ATL_OWNER { get; set; }
        public byte[] F_ATL_BRANCH { get; set; }
        public string F_NAME { get; set; }
        public string F_CODE { get; set; }
        public string F_ABBR { get; set; }
        public int F_WTYPE { get; set; }
        public int F_WTYPEMASK { get; set; }
        public byte[] F_CTYPEED { get; set; }
        public int F_WTYPELOAD { get; set; }
        public byte F_ISFIRSTWAVE { get; set; }
        public int F_WADDFLD_1_ { get; set; }
        public int F_WADDFLD_2_ { get; set; }
        public int F_WADDFLD_3_ { get; set; }
        public int F_WADDFLD_4_ { get; set; }
        public int F_WADDFLD_5_ { get; set; }
        public byte[] F_CADDFLD_1_ { get; set; }
        public byte[] F_CADDFLD_2_ { get; set; }
        public byte[] F_CADDFLD_3_ { get; set; }
        public byte[] F_CADDFLD_4_ { get; set; }
        public byte[] F_CADDFLD_5_ { get; set; }
        public decimal F_DADDFLD_1_ { get; set; }
        public decimal F_DADDFLD_2_ { get; set; }
        public decimal F_DADDFLD_3_ { get; set; }
        public decimal F_DADDFLD_4_ { get; set; }
        public decimal F_DADDFLD_5_ { get; set; }
        public string F_SADDFLD_1_ { get; set; }
        public string F_SADDFLD_2_ { get; set; }
        public string F_SADDFLD_3_ { get; set; }
        public string F_SADDFLD_4_ { get; set; }
        public string F_SADDFLD_5_ { get; set; }
    }
}
