//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFAA.DBAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class wkardc_rp
    {
        public int npp { get; set; }
        public int fnpp { get; set; }
        public string ncontract { get; set; }
        public Nullable<double> stavka { get; set; }
        public string sovm { get; set; }
        public Nullable<System.DateTime> du { get; set; }
        public Nullable<int> @struct { get; set; }
        public string struct_state { get; set; }
        public string prudal { get; set; }
        public string dolgnost { get; set; }
        public Nullable<System.DateTime> dr { get; set; }
        public string user { get; set; }
        public string kategoria { get; set; }
        public Nullable<bool> outsource { get; set; }
        public Nullable<System.Guid> guid { get; set; }
        public string C1cnpp { get; set; }
        public Nullable<System.DateTime> di { get; set; }
        public string ipphone { get; set; }
        public Nullable<System.DateTime> dn { get; set; }
        public Nullable<System.DateTime> @do { get; set; }
        public string vpo1cat { get; set; }
        public Nullable<int> otp { get; set; }
        public Nullable<int> year_mpps { get; set; }
        public string ВидДоговора { get; set; }
    }
}
